### ISSUE TITLE
Error in 'short_variants:get_somatic_vcfs:smurf', AttributeError: 'NoneType' object has no attribute 'append'

### ISSUE THREAD

**Issue by ssschulz** [ToolsVanBox/PTATO#8]
I get an error at the short_variants:get_somatic_vcfs:smurf, seems like some vcf, row or other object being passed into smurf is empty or otherwise not assigned properly. Is there something more specific regarding why this error is occuring and how I can fix? Bulk and non-bulk vcf files contain mutations for each sample. More detailed log file is attached.

[slurm-15128053.txt](https://github.com/ToolsVanBox/PTATO/files/11277441/slurm-15128053.txt)

**Comment by fulviodan13** [comment]
I got the same error. I think it still depend on the chromosome annotation (with prefix "chr"), just like the issue with #shapeit.

I am trying to bypass it modifing SMuRF.py by removing the line #146
`chr = re.sub("chr|chrom", "", chr)`
but it did not work.

Do you think we need to redo the alignment using a reference without chr prefix?

Any other suggestion?

Thank you!

**Comment by fulviodan13** [comment]
`bash /smurf/scripts/split_in_single_sample_vcfs.sh joint_output-hc.g.SMuRF.filtered.vcf

…

 

Command error:

    File "/usr/local/lib/python3.6/multiprocessing/process.py", line 93, in run

      self._target(*self._args, **self._kwargs)

    File "/smurf/SMuRF.py", line 175, in parse_chr_vcf

      record.FILTER.append('BadMQ')

  AttributeError: 'NoneType' object has no attribute 'append'

  Process Process-16:

  Traceback (most recent call last):

    File "/usr/local/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap

      self.run()

    File "/usr/local/lib/python3.6/multiprocessing/process.py", line 93, in run

      self._target(*self._args, **self._kwargs)

    File "/smurf/SMuRF.py", line 171, in parse_chr_vcf

      record.FILTER.append('BadQual')`

**Comment by mroosmalen** [comment]
Is it possible to share (a part) the input vcf file of SMuRF, so I can try to reproduce your errors and try to fix them.

**Comment by ssschulz** [comment]
[condensed.vcf.gz](https://github.com/ToolsVanBox/PTATO/files/11288623/condensed.vcf.gz)

Thanks!

**Comment by mroosmalen** [comment]
Thanks for sharing your data. The problem is that your vcfs don't have any data in the FILTER column. I'm working on a new lease which will fix this error (I hope). I will let you know when the new version is releasesd

**Comment by fulviodan13** [comment]
Thank you, Mark.

Do you mean the initial multi-sample VCF input generated by GATK, or the one generated in the output/intermediate/germline/ directory?

I did not understand which one is the input for SMURF.

What could be the reason I do not have any value in the FILTER column?

Thanks!

**Comment by domivika** [comment]
Hello @fulviodan13 
I see it's been a while since you worked with this tool, but could you tell me how did you manage to successfully get ab tables? In another issue I see you removed chr prefix from the input vcf file. Did you redo the alignment to the reference without the chr prefix and all the following steps such as haplotype calling etc? 
Thanks!
